### ISSUE TITLE
Where is the GPSARSAController code?

### ISSUE THREAD

**Issue by alexandr** [superfan89/GP-RL#1]
Just wondering since I'm working on this, where is the implementation of the actual GPSARSA agent?

Thanks!

**Comment by superfan89** [comment]
The RL training is implemented in [GPController.scala](https://github.com/superfan89/GP-RL/blob/master/src/main/scala/com/hccl/nlip/GPController.scala#L160-L240) and the trained policy is [here](https://github.com/superfan89/GP-RL/blob/master/src/main/scala/com/hccl/nlip/GPController.scala#L121-L130)
The implementation is rather a direct mapping from Engel's original description. But I cannnot guarantee its correctness.

Thanks for your attention.
